### ISSUE TITLE
Remove node version 

### ISSUE THREAD

**Issue by damienh** [RaspberryPiFoundation/Bits#58]
Setting up this morning updating my dependencies on slash learning failed as Bits required `node 8.5.x` where as Slash Learning required `8.9.0`. 

I got around this by passing `--ignore-engines`. 

Greg and David noted that as Bits is a front end dependency it shoudnt be governing node version. Though I know the plan is to have Bits as a stand alone React app.

**Comment by dtt101** [comment]
Yeah - a node version is fine, but it should be super forgiving, like:

```
  "engines": {
    "node": ">=6"
  },
```
