### ISSUE TITLE
Image-card layout on smaller devices

### ISSUE THREAD

**Issue by gregorywood** [RaspberryPiFoundation/Bits#60]
Initially highlighted here https://github.com/RaspberryPiFoundation/slash-learning-ui/issues/656

On a <768px screen width:

* The images are too large
* As a result each card takes up too much space, which is not ideal for a listing page where a key user action is to skim lots of content

Consider an alternative layout, perhaps with a thumbnail image to left of the text

**Comment by aldreth** [comment]
I added a temporary fix for /learning here https://github.com/RaspberryPiFoundation/slash-learning-ui/pull/773
