### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by aldreth** [RaspberryPiFoundation/Bits#85]
@Jonic Bits is really useful - I particularly like `.o-grid--rev` & the responsive margin & padding utilities.

**BUT** unless you understand iotacss & hold all the scss variables in your head, it's really hard to use! The iota documentation is about how to set it all up, rather than how to use it once built. http://www.iotacasts.com have been the most useful documentation so far, but videos are not suitable for quickly checking out the available classes for eg color. Also because all the iota setting names are can be over ridden it's hard to tell if the minimal iota docs are going to be relevant or not.

I've had https://static.raspberrypi.org/styles/Bits/1.1.7/Bits.min.css open in my browser and have been searching it for things like `u-mt` to see what the available sizes are, what the breakpoints are etc. It'd be great to have proper documentation!

**Comment by Jonic** [comment]
@aldreth Agreed - I've made a start at proper documentation in this PR (https://github.com/RaspberryPiFoundation/Bits/pull/61), but it's gotten kind of out of control, so if @dtt101 Can find time to let myself and @gregorywood do some more work I'll be concentrating on making it more accessible to "devs who are not me" :)

**Comment by Jonic** [comment]
Also might be worth me updating the files in the settings directory to explain how to actually apply the styles that the vars set up.
